/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'purchaseDate' : IDL.Int,
  'totalCents' : IDL.Nat,
  'productId' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'quantity' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'stripeSessionId' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'priceCents' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderPaymentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'purchaseDate' : IDL.Int,
    'totalCents' : IDL.Nat,
    'productId' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'quantity' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'stripeSessionId' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderPaymentStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };